##Example Bash script for preparing bam files from fastq for processing in vitro DiMeLoseq data
##Generated by Owen K Smith, curated by Kousik Sundararajan

#DiMeLo_in_vitro_processing
##### guppy with basecalling and fast config for fast5 spliting 
/path/to/ont-guppy/bin/guppy_basecaller --input_path /path/to/input/fast5 --save_path /path/to/output/full_fast_gpu --config /path/to/config/ont-guppy/data/dna_r9.4.1_450bps_fast.cfg --num_callers *cpus* --fast5_out
##demultiplex, split fastq of full
/path/to/ont-guppy/bin/guppy_barcoder --input_path /path/to/output/full_fast_gpu --save_path /path/to/output/full_fast_gpu/split/ --config /path/to/config/ont-guppy/data/barcoding/configuration.cfg -t *cpus*
cd /path/to/output/full_fast_gpu/split/
#for each barcode used
#get list of readids in each barcode
for bar in 01 02 03 04 05 06 07 08 09 10 11 12;
do
    for file in './barcode'$bar'/*fastq';
    do
    awk -F '[ ]' 'BEGIN {OFS="\n"}(NR%4==1){print $1}' $file | sed -e 's/^.//' >> './barcode'$bar'/barcode'$bar'_readids.txt'
    done
done
##split raw fast5s by barcode readids to run through megalodon
source activate ont 
###need to mkdir for outputdirs ./fast5_split and for each ./fast5_split/barcode0*
cd /path/to/output/full_fast_gpu
mkdir fast5_split
for n in 01 02 03 04 05 06 07 08 09 10 11 12;
do
mkdir 'fast5_split/barcode'$n
done
for n in 01 02 03 04 05 06 07 08 09 10 11 12;
do
fast5_subset -i /path/to/input/fast5 -s '/path/to/output/full_fast_gpu/fast5_split/barcode'$n -l '/path/to/output/full_fast_gpu/split/barcode'$n'/barcode'$n'_readids.txt' -n 2000000 -t 32 
done
#### run megalodon to basecall on 18x601
for n in 01 02 03 04 05 06 07 08 09 10 11 12;
do
megalodon '/path/to/output/full_fast_gpu/fast5_split/barcode'$n --outputs basecalls mod_basecalls mappings mod_mappings mods per_read_mods --output-directory '/path/to/megalodon/output/bar'$n --reference /path/to/ASP696_18x601.fa --guppy-server-path /path/to/ont-guppy/bin/guppy_basecall_server --guppy-config res_dna_r941_min_modbases-all-context_v001.cfg --guppy-params "-d /path/to/rerio/basecall_models/ --num_callers 30 --barcode_kits 'EXP-NBD104' --trim_barcodes" --reads-per-guppy-batch 10 --guppy-timeout 360 --mod-min-prob 0
##use sbatch to sumbit for all barcodes
####only get reads of exact length of full array
ml devel java
cd /path/to/megalodon/output/
for n in 1 2 3 4 5 6 7 8 9 10 11 12;
do
/path/to/reformat.sh in='/path/to/megalodon/output/bar'$n'/mod_mappings.bam' out='/path/to/megalodon/output/bar'$n'/mod_mappings_3.6kb.bam' minlength=3600 ref=/path/to/ASP696_18x601.fa
done
